import { useRouter } from "next/router";
import Head from "next/head";
import { NextPage } from "next";
import { useEffect } from "react";
import connectToDatabase from "../../mongodb";
import { COLLECTION_NAMES } from "../../types";

const HashPage: NextPage = () => {
  const router = useRouter();

  useEffect(() => {
    async function fetchData() {
      const hash = router.query.hash as string;
      const database = await connectToDatabase();
      const campaign = await database
        .collection(COLLECTION_NAMES["url-info"])
        .findOne({ uid: hash });

      if (campaign) {
        window.location.href = campaign.link;
      }
    }

    fetchData();
  }, [router.query.hash]);

  return (
    <div>
      <Head>
        <title>URL Shortener</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Requested link not found</h1>
    </div>
  );
};

export default HashPage;